public class CommandsData
{
    static private string[] _Adjectives =
    {
        "aback" , "abaft" , "abandoned" , "abashed" , "aberrant" , "abhorrent" , "abiding" , "abject" , "ablaze" , "able" , "abnormal" , "aboard" , "aboriginal" , "abortive" , "abounding" , "abrasive" , "abrupt" , "absent" , "absorbed" , "absorbing" , "abstracted" , "absurd" , "abundant" , "abusive" , "acceptable" , "accessible" ,
        "accidental" , "accurate" , "acid" , "acidic" , "acoustic" , "acrid" , "actually" , "ad" , "hoc" , "adamant" , "adaptable" , "addicted" , "adhesive" , "adjoining" , "adorable" , "adventurous" , "afraid" , "aggressive" , "agonizing" , "agreeable" , "ahead" , "ajar" , "alcoholic" , "alert" , "alike" , "alive" , "alleged" , "alluring" , "aloof" ,
        "amazing" , "ambiguous" , "ambitious" , "amuck" , "amused" , "amusing" , "ancient" , "angry" , "animated" , "annoyed" , "annoying" , "anxious" , "apathetic" , "aquatic" , "aromatic" , "arrogant" , "ashamed" , "aspiring" , "assorted" , "astonishing" , "attractive" , "auspicious" , "automatic" , "available" , "average" , "awake" , "aware" ,
        "awesome" , "awful" , "axiomatic",
        "bad" , "barbarous" , "bashful" , "bawdy" , "beautiful" , "befitting" , "belligerent" , "beneficial" , "bent" , "berserk" , "best" , "better" , "bewildered" , "big" , "billowy" , "bite-sized" , "bitter" , "bizarre" , "black" , "black-and-white" , "bloody" , "blue" , "blue-eyed" , "blushing" , "boiling" , "boorish" , "bored" , "boring" ,
        "bouncy" , "boundless" , "brainy" , "brash" , "brave" , "brawny" , "breakable" , "breezy" , "brief" , "bright" , "bright" , "broad" , "broken" , "brown" , "bumpy" , "burly" , "bustling" , "busy" ,
        "cagey" , "calculating" , "callous" , "calm" , "capable" , "capricious" , "careful" , "careless" , "caring" , "cautious" , "ceaseless" , "certain" , "changeable" , "charming" , "cheap" , "cheerful" , "chemical" , "chief" , "childlike" , "chilly" , "chivalrous" , "chubby" , "chunky" , "clammy" , "classy" , "clean" , "clear" , "clever" ,
        "cloistered" , "cloudy" , "closed" , "clumsy" , "cluttered" , "coherent" , "cold" , "colorful" , "colossal" , "combative" , "comfortable" , "common" , "complete" , "complex" , "concerned" , "condemned" , "confused" , "conscious" , "cooing" , "cool" , "cooperative" , "coordinated" , "courageous" , "cowardly" , "crabby" , "craven" ,
        "crazy" , "creepy" , "crooked" , "crowded" , "cruel" , "cuddly" , "cultured" , "cumbersome" , "curious" , "curly" , "curved" , "curvy" , "cut" , "cute" , "cute" , "cynical" ,
        "daffy" , "daily" , "damaged" , "damaging" , "damp" , "dangerous" , "dapper" , "dark" , "dashing" , "dazzling" , "dead" , "deadpan" , "deafening" , "dear" , "debonair" , "decisive" , "decorous" , "deep" , "deeply" , "defeated" , "defective" , "defiant" , "delicate" , "delicious" , "delightful" , "demonic" , "delirious" , "dependent" ,
        "depressed" , "deranged" , "descriptive" , "deserted" , "detailed" , "determined" , "devilish" , "didactic" , "different" , "difficult" , "diligent" , "direful" , "dirty" , "disagreeable" , "disastrous" , "discreet" , "disgusted" , "disgusting" , "disillusioned" , "dispensable" , "distinct" , "disturbed" , "divergent" ,
        "dizzy" , "domineering" , "doubtful" , "drab" , "draconian" , "dramatic" , "dreary" , "drunk" , "dry" , "dull" , "dusty" , "dusty" , "dynamic" , "dysfunctional",
        "eager" , "early" , "earsplitting" , "earthy" , "easy" , "eatable" , "economic" , "educated" , "efficacious" , "efficient" , "eight" , "elastic" , "elated" , "elderly" , "electric" , "elegant" , "elfin" , "elite" , "embarrassed" , "eminent" , "empty" , "enchanted" , "enchanting" , "encouraging" , "endurable" , "energetic" , "enormous" ,
        "entertaining" , "enthusiastic" , "envious" , "equable" , "equal" , "erect" , "erratic" , "ethereal" , "evanescent" , "evasive" , "even" , "excellent" , "excited" , "exciting" , "exclusive" , "exotic" , "expensive" , "extra-large" , "extra-small" , "exuberant" , "exultant" ,
        "fabulous" , "faded" , "faint" , "fair" , "faithful" , "fallacious" , "false" , "familiar" , "famous" , "fanatical" , "fancy" , "fantastic" , "far" , "far-flung" , "fascinated" , "fast" , "fat" , "faulty" , "fearful" , "fearless" , "feeble" , "feigned" , "female" , "fertile" , "festive" , "few" , "fierce" , "filthy" , "fine" , "finicky" , "first" , "five" ,
        "fixed" , "flagrant" , "flaky" , "flashy" , "flat" , "flawless" , "flimsy" , "flippant" , "flowery" , "fluffy" , "fluttering" , "foamy" , "foolish" , "foregoing" , "forgetful" , "fortunate" , "four" , "frail" , "fragile" , "frantic" , "free" , "freezing" , "frequent" , "fresh" , "fretful" , "friendly" , "frightened" , "frightening" , "full" ,
        "fumbling" , "functional" , "funny" , "furry" , "furtive" , "future" , "futuristic" , "fuzzy" ,
        "gabby", "gainful", "gamy", "gaping", "garrulous", "gaudy", "general", "gentle", "giant", "giddy", "gifted", "gigantic", "glamorous", "gleaming", "glib", "glistening", "glorious", "glossy", "godly", "good", "goofy", "gorgeous", "graceful", "grandiose", "grateful", "gratis", "gray", "greasy", "great", "greedy", "green", "grey",
        "grieving" , "groovy" , "grotesque" , "grouchy" , "grubby" , "gruesome" , "grumpy" , "guarded" , "guiltless" , "gullible" , "gusty" , "guttural" ,
        "habitual", "half", "hallowed", "halting", "handsome", "handsomely", "handy", "hanging", "hapless", "happy", "hard", "hard-to-find", "harmonious", "harsh", "hateful", "heady", "healthy", "heartbreaking", "heavenly", "heavy", "hellish", "helpful", "helpless", "hesitant", "hideous", "high", "highfalutin",
        "high - pitched" , "hilarious" , "hissing" , "historical" , "holistic" , "hollow" , "homeless" , "homely" , "honorable" , "horrible" , "hospitable" , "hot" , "huge" , "hulking" , "humdrum" , "humorous" , "hungry" , "hurried" , "hurt" , "hushed" , "husky" , "hypnotic" , "hysterical" ,
        "icky", "icy", "idiotic", "ignorant", "ill", "illegal", "ill-fated", "ill-informed", "illustrious", "imaginary", "immense", "imminent", "impartial", "imperfect", "impolite", "important", "imported", "impossible", "incandescent", "incompetent", "inconclusive", "industrious", "incredible", "inexpensive",
        "infamous" , "innate" , "innocent" , "inquisitive" , "insidious" , "instinctive" , "intelligent" , "interesting" , "internal" , "invincible" , "irate" , "irritating" , "itchy" ,
        "jaded" , "jagged" , "jazzy" , "jealous" , "jittery" , "jobless" , "jolly" , "joyous" , "judicious" , "juicy" , "jumbled" , "jumpy" , "juvenile" ,
        "kaput" , "keen" , "kind" , "kindhearted" , "kindly" , "knotty" , "knowing" , "knowledgeable" , "known" ,
        "labored" , "lackadaisical" , "lacking" , "lame" , "lamentable" , "languid" , "large" , "last" , "late" , "laughable" , "lavish" , "lazy" , "lean" , "learned" , "left" , "legal" , "lethal" , "level" , "lewd" , "light" , "like" , "likeable" , "limping" , "literate" , "little" , "lively" , "lively" , "living" , "lonely" , "long" , "longing" , "long-term" , 
        "loose" , "lopsided" , "loud" , "loutish" , "lovely" , "loving" , "low" , "lowly" , "lucky" , "ludicrous" , "lumpy" , "lush" , "luxuriant" , "lying" , "lyrical" ,
        "macabre" , "macho" , "maddening" , "madly" , "magenta" , "magical" , "magnificent" , "majestic" , "makeshift" , "male" , "malicious" , "mammoth" , "maniacal" , "many" , "marked" , "massive" , "married" , "marvelous" , "material" , "materialistic" , "mature" , "mean" , "measly" , "meaty" , "medical" , "meek" , "mellow" , "melodic" , "melted" , 
        "merciful" , "mere" , "messy" , "mighty" , "military" , "milky" , "mindless" , "miniature" , "minor" , "miscreant" , "misty" , "mixed" , "moaning" , "modern" , "moldy" , "momentous" , "motionless" , "mountainous" , "muddled" , "mundane" , "murky" , "mushy" , "mute" , "mysterious",
        "naive" , "nappy" , "narrow" , "nasty" , "natural" , "naughty" , "nauseating" , "near" , "neat" , "nebulous" , "necessary" , "needless" , "needy" , "neighborly" , "nervous" , "new" , "next" , "nice" , "nifty" , "nimble" , "nine" , "nippy" , "noiseless" , "noisy" , "nonchalant" , "nondescript" , "nonstop" , "normal" , "nostalgic" , "nosy" , "noxious" , 
        "null" , "numberless" , "numerous" , "nutritious" , "nutty",
        "oafish" , "obedient" , "obeisant" , "obese" , "obnoxious" , "obscene" , "obsequious" , "observant" , "obsolete" , "obtainable" , "oceanic" , "odd" , "offbeat" , "old" , "old-fashioned" , "omniscient" , "one" , "onerous" , "open" , "opposite" , "optimal" , "orange" , "ordinary" , "organic" , "ossified" , "outgoing" , "outrageous" , 
        "outstanding" , "oval" , "overconfident" , "overjoyed" , "overrated" , "overt" , "overwrought",
        "painful" , "painstaking" , "pale" , "paltry" , "panicky" , "panoramic" , "parallel" , "parched" , "parsimonious" , "past" , "pastoral" , "pathetic" , "peaceful" , "penitent" , "perfect" , "periodic" , "permissible" , "perpetual" , "petite" , "petite" , "phobic" , "physical" , "picayune" , "pink" , "piquant" , "placid" , "plain" , 
        "plant" , "plastic" , "plausible" , "pleasant" , "plucky" , "pointless" , "poised" , "polite" , "political" , "poor" , "possessive" , "possible" , "powerful" , "precious" , "premium" , "present" , "pretty" , "previous" , "pricey" , "prickly" , "private" , "probable" , "productive" , "profuse" , "protective" , "proud" , "psychedelic" , 
        "psychotic" , "public" , "puffy" , "pumped" , "puny" , "purple" , "purring" , "pushy" , "puzzled" , "puzzling",
        "quack" , "quaint" , "quarrelsome" , "questionable" , "quick" , "quickest" , "quiet" , "quirky" , "quixotic" , "quizzical",
        "rabid" , "racial" , "ragged" , "rainy" , "rambunctious" , "rampant" , "rapid" , "rare" , "raspy" , "ratty" , "ready" , "real" , "rebel" , "receptive" , "recondite" , "red" , "redundant" , "reflective" , "regular" , "relieved" , "remarkable" , "reminiscent" , "repulsive" , "resolute" , "resonant" , "responsible" , "rhetorical" , "rich" , 
        "right" , "righteous" , "rightful" , "rigid" , "ripe" , "ritzy" , "roasted" , "robust" , "romantic" , "roomy" , "rotten" , "rough" , "round" , "royal" , "ruddy" , "rude" , "rural" , "rustic" , "ruthless",
        "sable" , "sad" , "safe" , "salty" , "same" , "sassy" , "satisfying" , "savory" , "scandalous" , "scarce" , "scared" , "scary" , "scattered" , "scientific" , "scintillating" , "scrawny" , "screeching" , "second" , "second-hand" , "secret" , "secretive" , "sedate" , "seemly" , "selective" , "selfish" , "separate" , "serious" , "shaggy" , 
        "shaky" , "shallow" , "sharp" , "shiny" , "shivering" , "shocking" , "short" , "shrill" , "shut" , "shy" , "sick" , "silent" , "silent" , "silky" , "silly" , "simple" , "simplistic" , "sincere" , "six" , "skillful" , "skinny" , "sleepy" , "slim" , "slimy" , "slippery" , "sloppy" , "slow" , "small" , "smart" , "smelly" , "smiling" , "smoggy" , "smooth" , "sneaky" , 
        "snobbish" , "snotty" , "soft" , "soggy" , "solid" , "somber" , "sophisticated" , "sordid" , "sore" , "sore" , "sour" , "sparkling" , "special" , "spectacular" , "spicy" , "spiffy" , "spiky" , "spiritual" , "spiteful" , "splendid" , "spooky" , "spotless" , "spotted" , "spotty" , "spurious" , "squalid" , "square" , "squealing" , "squeamish" , 
        "staking" , "stale" , "standing" , "statuesque" , "steadfast" , "steady" , "steep" , "stereotyped" , "sticky" , "stiff" , "stimulating" , "stingy" , "stormy" , "straight" , "strange" , "striped" , "strong" , "stupendous" , "stupid" , "sturdy" , "subdued" , "subsequent" , "substantial" , "successful" , "succinct" , "sudden" , "sulky" , 
        "super" , "superb" , "superficial" , "supreme" , "swanky" , "sweet" , "sweltering" , "swift" , "symptomatic" , "synonymous",
        "taboo" , "tacit" , "tacky" , "talented" , "tall" , "tame" , "tan" , "tangible" , "tangy" , "tart" , "tasteful" , "tasteless" , "tasty" , "tawdry" , "tearful" , "tedious" , "teeny" , "teeny-tiny" , "telling" , "temporary" , "ten" , "tender" , "tense" , "tense" , "tenuous" , "terrible" , "terrific" , "tested" , "testy" , "thankful" , "therapeutic" , 
        "thick" , "thin" , "thinkable" , "third" , "thirsty" , "thirsty" , "thoughtful" , "thoughtless" , "threatening" , "three" , "thundering" , "tidy" , "tight" , "tightfisted" , "tiny" , "tired" , "tiresome" , "toothsome" , "torpid" , "tough" , "towering" , "tranquil" , "trashy" , "tremendous" , "tricky" , "trite" , "troubled" , "truculent" , 
        "true" , "truthful" , "two" , "typical",
        "ubiquitous" , "ugliest" , "ugly" , "ultra" , "unable" , "unaccountable" , "unadvised" , "unarmed" , "unbecoming" , "unbiased" , "uncovered" , "understood" , "undesirable" , "unequal" , "unequaled" , "uneven" , "unhealthy" , "uninterested" , "unique" , "unkempt" , "unknown" , "unnatural" , "unruly" , "unsightly" , 
        "unsuitable" , "untidy" , "unused" , "unusual" , "unwieldy" , "unwritten" , "upbeat" , "uppity" , "upset" , "uptight" , "used" , "useful" , "useless" , "utopian" , "utter" , "uttermost",
        "vacuous" , "vagabond" , "vague" , "valuable" , "various" , "vast" , "vengeful" , "venomous" , "verdant" , "versed" , "victorious" , "vigorous" , "violent" , "violet" , "vivacious" , "voiceless" , "volatile" , "voracious" , "vulgar",
        "wacky" , "waggish" , "waiting" , "wakeful" , "wandering" , "wanting" , "warlike" , "warm" , "wary" , "wasteful" , "watery" , "weak" , "wealthy" , "weary" , "well-groomed" , "well-made" , "well-off" , "well-to-do" , "wet" , "whimsical" , "whispering" , "white" , "whole" , "wholesale" , "wicked" , "wide" , "wide-eyed" , "wiggly" , 
        "wild" , "willing" , "windy" , "wiry" , "wise" , "wistful" , "witty" , "woebegone" , "womanly" , "wonderful" , "wooden" , "woozy" , "workable" , "worried" , "worthless" , "wrathful" , "wretched" , "wrong" , "wry"
    };

    static private string[] _Nouns =
    {
        "A-frame" , "Aard-vark" , "Aard-wolf" , "Aber-de-vine" , "About-face" , "About-sledge" , "Aboveboard" , "Abraham-man" , "Abram-man" , "Absey-book" ,
        "Ace-in-the-hole" , "Ack-ack" , "Acorn-shell" , "Acre-foot" , "Acted-upon" , "Acting-up" , "Actino-chemistry" , "Active-wear" , "Add-in" , "Add-ins" ,
        "Add-on" , "Add-ons" , "Adder's-tongue" , "Addle-brain" , "Addle-head" , "Addle-pate" , "Addle-patedness" , "Advisable-ness" , "Aestho-physiology" , "After-care" ,
        "After-eatage" , "After-effect" , "After-effects" , "After-glow" , "After-image" , "After-images" , "After-life" , "After-market" , "After-note" , "After-sails" ,
        "After-shave" , "After-shock" , "After-shocks" , "After-thought" , "After-wit" , "Afterbirth" , "Afterglow" , "Afterimage" , "Afterlife" , "Aftermath" , "Afternoon" ,
        "Afterthought" , "Agal-agal" , "Agar-agar" , "Aid-de-camp" , "Aid-major" , "Aide-de-camp" , "Air-conditioner" , "Air-tight" , "Air-traffic" , "Airborne" , "Aircraft" ,
        "Airfield" , "Airlift" , "Airline" , "Airmail" , "Airmen" , "Airplane" , "Airport" , "Airtight" , "Airtime" , "Al-phitomancy" , "Ale-knight" , "All-clear" , "All-nighter" ,
        "All-nighters" , "All-rounder" , "All-rounders" , "Allover" , "Allspice" , "Alongside" , "Also" , "Also-ran" , "Also-rans" , "Alter-ego" , "Alto-relievo" , "Alto-rilievo" ,
        "Ambassador-at-large" , "Ambes-as" , "Ambs-ace" , "Ames-ace" , "Amino-acid" , "Amino-acids" , "Amuse-gueules" , "Anchor-hold" , "Anchorperson" , "Anglo-" , "Catholic" , "Anglo-" ,
        "Saxon" , "Anglo-" , "Saxondom" , "Anglo-" , "Saxonism" , "Another" , "Ant-bear" , "Ant-cattle" , "Ant-eater" , "Ant-hill" , "Ant-lion" , "Anti-bodies" , "Anti-capitalism" ,
        "Anti-climax" , "Anti-communism" , "Anti-communist" , "Anti-communists" , "Anti-fascists" , "Anti-federalist" , "Anti-foreign" , "Anti-freeze" , "Anti-hero" , "Anti-intellectualism" ,
        "Anti-matter" , "Anti-monarchists" , "Anti-oxidants" , "Anti-popery" , "Anti-popes" , "Anti-racism" , "Anti-racist" , "Anti-racists" , "Anti-realism" , "Anti-riot" , "Anti-romanticism" ,
        "Anti-semite" , "Anti-semitism" , "Anti-sera" , "Anti-smoker" , "Anti-smokers" , "Anti-trade" , "Anti-tumor" , "Anti-virus" , "Antic-mask" , "Anybody" , "Anyhow" , "Anymore" , "Anyone" ,
        "Anyplace" , "Anything" , "Anytime" , "Anyway" , "Anywhere" , "Apple-jack" , "Apple-john" , "Apple-squire" , "Applesauce" , "Arm-in-arm" , "Armchair" , "Armor-bearer" , "Armpit" , "Around" ,
        "Arriere-ban" , "Ash-fire" , "Ash-furnace" , "Ash-oven" , "Ashtray" , "At-bat" , "At-home" , "Attorney-at-law" , "Attorney-general" , "Audiotape" , "Auto-da-fe" , "Auto-de-fe" , "Avant-courier" ,
        "Avant-garde" , "Avant-guard" , "Awestruck" , "Aye-aye" , "Babysitter" , "Bachelor-girl" , "Back-down" , "Back-packed" , "Back-up" , "Backache" , "Backbite" , "Backboard" , "Backbone" , "Backbreaker" ,
        "Backbreaking" , "Backdrop" , "Backfire" , "Background" , "Backhand" , "Backlash" , "Backlog" , "Backpack" , "Backside" , "Backslap" , "Backslide" , "Backspace" , "Backspin" , "Backstage" , "Backstroke" ,
        "Backtrack" , "Backup" , "Backward" , "Backwoods" , "Backyard" , "Bain-marie" , "Baked-meat" , "Balance-of-payments" , "Ball-flower" , "Ball-park" , "Ball-up" , "Ballpark" , "Ballroom" , "Bandwagon" ,
        "Bankbook" , "Banknote" , "Bankroll" , "Bar-room" , "Barefoot" , "Barley-bree" , "Barman" , "Baryto-calcite" , "Bas-relief" , "Base-burner" , "Base-court" , "Baseball" , "Bashi-bazouk" , "Basketball" ,
        "Bass-relief" , "Basso-relievo" , "Basso-rilievo" , "Bathroom" , "Battering-ram" , "Battle-ax" , "Battle-axe" , "Bay-antler" , "Be-all" , "Be-all-and-end-all" , "Be-bop" , "Be-cause" , "Bear's-breech" ,
        "Bear's-ear" , "Bear's-foot" , "Bear's-paw" , "Became" , "Because" , "Become" , "Bed-molding" , "Bed-moulding" , "Bedclothes" , "Bedrock" , "Bedroll" , "Bedroom" , "Bedspread" , "Bedtime" , "Bee-eater" ,
        "Beef-witted" , "Beefing-up" , "Beeswax" , "Beforehand" , "Bel-accoyle" , "Bel-esprit" , "Bellbottom" , "Bellboy" , "Belle-lettrist" , "Belles-lettres" , "Bellhop" , "Belly-button" , "Belly-god" , "Below" ,
        "Below-the-line" , "Benchmark" , "Bes-antler" , "Best-seller" , "Best-selling" , "Bez-antler" , "Bibble-babble" , "Big-bang" , "Big-headed" , "Big-heads" , "Billboard" , "Billet-doux" , "Bird's-beak" ,
        "Bird's-eye" , "Bird's-foot" , "Bird's-mouth" , "Bird's-nest" , "Bird's-nesting" , "Bird's-tongue" , "Bird-song" , "Birdhouse" , "Birthday" , "Birthright" , "Bishop's-weed" , "Bishop's-wort" , "Bishop-stool" ,
        "Black-jack" , "Black-listed" , "Blackball" , "Blackberries" , "Blackberry" , "Blackbird" , "Blackboard" , "Blackjack" , "Blacklist" , "Blackmail" , "Blackout" , "Blacksmith" , "Blacktop" , "Blast-off" ,
        "Blasted-off" , "Blasts-off" , "Blood-relatives" , "Bloodvessel" , "Blow-out" , "Blow-up" , "Blowgun" , "Blowup" , "Blue-bonnet" , "Blue-eye" , "Blue-green" , "Blue-john" , "Bluebell" , "Blueberry" ,
        "Bluebird" , "Bluefish" , "Bluegrass" , "Blueprint" , "Blunt-witted" , "Boardwalk" , "Boat-tail" , "Bob-cherry" , "Bodyguard" , "Bodywork" , "Bog-eyed" , "Boldface" , "Bolthole" , "Bon-accord" ,
        "Boo-boo" , "Bookcase" , "Bookend" , "Booking-in" , "Bookkeeper" , "Bookmark" , "Bookmobile" , "Bookseller" , "Bookshelf" , "Bookstore" , "Bookworm" , "Bootstrap" , "Booze-up" , "Bore-hole" , "Borough-" ,
        "English" , "Both-hands" , "Bottle-green" , "Bottle-nose" , "Bouts-rimes" , "Bow-bells" , "Bow-compass" , "Bow-legged" , "Bow-pen" , "Bow-pencil" , "Bow-saw" , "Bowlegs" , "Bowtie" , "Box-iron" , "Boyfriend" ,
        "Brahmo-somaj" , "Brainchild" , "Brainstorm" , "Brainwash" , "Brant-fox" , "Breach-of-contract" , "Break-circuit" , "Break-in" , "Break-off" , "Breakdown" , "Breakfast" , "Breakout" , "Breakthrough" , "Breakup" ,
        "Breathtaking" , "Bric-a brac" , "Bric-a-brac" , "Bride-ale" , "Bridge-ward" , "Bridle-path" , "Broad-swords" , "Broadcast" , "Broken-winded" , "Broncho-pneumonia" , "Brother-in-law" , "Brush-off" ,
        "Brushwood" , "Buck's-horn" , "Buck-basket" , "Build-up" , "Buildup" , "Bulbo-tuber" , "Bull's-eye" , "Bull's-nose" , "Bull-like" , "Bulldog" , "Bullen-bullen" , "Bullen-nail" , "Bullfight" , "Bullock's-eye" ,
        "Bumble-bee" , "Bumble-bees" , "Burgess-ship" , "Burnout" , "Burnt-offering" , "Bush-telegraph" , "Bust-up" , "But-thorn" , "Butter-scotch" , "Butterball" , "Buttercup" , "Butterfingers" , "Butterflies" ,
        "Butterfly" , "Buttermilk" , "Butternut" , "Butterscotch" , "Buy-back" , "Buy-in" , "Buzz-word" , "Buzz-words" , "By-and-by" , "By-bidder" , "By-blow" , "By-corner" , "By-dependence" , "By-drinking" ,
        "By-election" , "By-elections" , "By-end" , "By-interest" , "By-lane" , "By-law" , "By-line" , "By-name" , "By-pass" , "By-passage" , "By-passing" , "By-place" , "By-product" , "By-respect" , "By-road" ,
        "By-roads" , "By-room" , "By-speech" , "By-spell" , "By-street" , "By-stroke" , "By-turning" , "By-view" , "By-walk" , "By-wash" , "By-wipe" , "By-word" , "By-your-leave" , "Bye-bye" , "Bypass" , "Byproduct" ,
        "Cabdriver" , "Calc-sinter" , "Calc-spar" , "Calc-tufa" , "Call-in" , "Call-up" , "Cambro-" , "Briton" , "Campfire" , "Can" , "Cancan" , "Candlelight" , "Candlestick" , "Cannot" , "Cardboard" , "Cardsharp" ,
        "Cardstock" , "Carefree" , "Caregiver" , "Caretaker" , "Careworn" , "Carfare" , "Cargo" , "Carhop" , "Carload" , "Carnal-mindedness" , "Carpet" , "Carpetbagger" , "Carpool" , "Carport" , "Carrack" ,
        "Carry-over" , "Carryall" , "Carryover" , "Carsick" , "Cartwheel" , "Case-bay" , "Cash-in" , "Castle-guard" , "Cat's-eye" , "Cat's-foot" , "Cat's-paw" , "Cat's-tail" , "Cat-harpin" , "Cat-harping" ,
        "Cat-hole" , "Cat-salt" , "Cat-silver" , "Cat-tail" , "Catch-basin" , "Catch-meadow" , "Catch-up" , "Cater-cousin" , "Catfish" , "Cato-cathartic" , "Cattail" , "Catwalk" , "Cave-in" , "Caved-in" ,
        "Caveman" , "Cavo-relievo" , "Cavo-rilievo" , "Cease-fire" , "Chain-of-command" , "Chairman" , "Chalkboard" , "Chance-medley" , "Change-of-heart" , "Chap-lain" , "Chapel-of-ease" , "Char-a-bancs" ,
        "Charge-off" , "Chat-show" , "Chaud-medley" , "Cheap-jack" , "Cheap-john" , "Cheapskate" , "Check-in" , "Check-out" , "Check-over" , "Checkout" , "Checkup" , "Cheek-by-jowl" , "Cheeseburger" , "Cheesecake" ,
        "Chef-d'oeuvre" , "Chess-apple" , "Chest-on-chest" , "Cheval-de-frise" , "Chiaro-oscuro" , "Chick-pea" , "Chief-justiceship" , "Chiff-chaff" , "Chimney-breast" , "Chimney-piece" , "Chip-in" , "Chipped-in" ,
        "Choke-strap" , "Chop-logic" , "Chopstick" , "Christ's-thorn" , "Chuck-" , "Will's-widow" , "Church-ale" , "Church-bench" , "Church-haw" , "Churchgoer" , "Cich-pea" , "Cinque-pace" , "Cirro-cumulus" ,
        "Cirro-stratus" , "Cittern-head" , "Citywide" , "Clair-obscur" , "Clamp-down" , "Clare-obscure" , "Claro-obscuro" , "Class-action" , "Classmate" , "Cleanup" , "Clear-sightedness" , "Clerk-ale" ,
        "Climb-down" , "Clipboard" , "Clockwise" , "Clockwork" , "Close-fights" , "Close-stool" , "Close-up" , "Close-ups" , "Clotheshorse" , "Clothesline" , "Cloud-burst" , "Cloud-compeller" , "Clowe-gilofre" ,
        "Club-rush" , "Clued-in" , "Co-agent" , "Co-ally" , "Co-assessor" , "Co-author" , "Co-authored" , "Co-chairman" , "Co-conspirator" , "Co-defendant" , "Co-discoverer" , "Co-editor" , "Co-efficient" ,
        "Co-founder" , "Co-heir" , "Co-heiress" , "Co-incidence" , "Co-inventor" , "Co-legatee" , "Co-lessee" , "Co-lessor" , "Co-mate" , "Co-operation" , "Co-ordination" , "Co-partner" , "Co-pilot" , "Co-product" ,
        "Co-recipient" , "Co-regent" , "Co-relation" , "Co-religionist" , "Co-respondent" , "Co-sponsor" , "Co-sponsored" , "Co-star" , "Co-starred" , "Co-starring" , "Co-stars" , "Co-sufferer" , "Co-winner" ,
        "Coach-and-four" , "Coal-meter" , "Coal-whipper" , "Coat-of-arms" , "Cobble-stones" , "Cock-of-the-rock" , "Cock-padle" , "Cockpit" , "Coffee-shop" , "Coffeemaker" , "Cold-shut" , "Colorblind" , "Come-on" ,
        "Come-outer" , "Comeback" , "Comedown" , "Comet- seeker" , "Comet-finder" , "Commander-in-chief" , "Commanders-in-chief" , "Commonplace" , "Commonsense" , "Commonwealth" , "Comrade-in-arms" , "Concert-goer" ,
        "Concho-spiral" , "Contracting-out" , "Conversazi-one" , "Cony-catcher" , "Cook-off" , "Cookbook" , "Cooperative" , "Cop-rose" , "Cope-chisel" , "Copper-nickel" , "Copper-nose" , "Copperhead" , "Copple-crown" ,
        "Copycat" , "Copyright" , "Coral-rag" , "Corbel-table" , "Cornerstone" , "Cornet-a-piston" , "Cornmeal" , "Cosmic-rays" , "Cost-of-living" , "Count-wheel" , "Countdown" , "Counter-attack" , "Counter-attacked" ,
        "Counter-balanced" , "Counter-cultural" , "Counter-measure" , "Counter-offensive" , "Counter-roll" , "Counter-terrorism" , "Country-base" , "Country-dance" , "Countryside" , "Coupe-gorge" , "Couple-beggar" ,
        "Couple-close" , "Court-baron" , "Court-craft" , "Court-cupboard" , "Court-leet" , "Court-martial" , "Court-martialing" , "Court-plaster" , "Courthouse" , "Courts-martial" , "Courtyard" , "Cousin-german" ,
        "Cover-point" , "Cover-shame" , "Cover-up" , "Cow-pilot" , "Cowboy" , "Crab-yaws" , "Crackdown" , "Crane's-bill" , "Craze-mill" , "Crazing-mill" , "Cream-fruit" , "Cream-slice" , "Creepy-crawlies" ,
        "Creepy-crawly" , "Crewcut" , "Crib-biter" , "Crib-biting" , "Crincum-crancum" , "Crisscross-row" , "Cro-quette" , "Crop-ear" , "Cross-bearer" , "Cross-birth" , "Cross-bun" , "Cross-crosslet" , "Cross-days" ,
        "Cross-examiner" , "Cross-eye" , "Cross-fertilization" , "Cross-garnet" , "Cross-over" , "Cross-pawl" , "Cross-purpose" , "Cross-reading" , "Cross-spale" , "Cross-spall" , "Cross-springer" , "Cross-staff" ,
        "Cross-stitch" , "Cross-stone" , "Cross-tail" , "Cross-tie" , "Cross-tining" , "Cross-vaulting" , "Cross-week" , "Crossbow" , "Crossbreed" , "Crosscut" , "Crossover" , "Crossroad" , "Crosswalk" , "Crow's-foot" ,
        "Crow's-nest" , "Crow-quill" , "Crow-silk" , "Crown-imperial" , "Crown-post" , "Crown-saw" , "Cubbridge-head" , "Cubo-octahedron" , "Cuff-link" , "Cul-de-sac" , "Cumu-cirro-stratus" , "Cup-gall" , "Cup-moss" ,
        "Cup-rose" , "Cupboard" , "Cupcake" , "Cure-all" , "Cut-out" , "Cutback" , "Daggle-tail" , "Dairymaid" , "Daisywheel" , "Damping-off" , "Dandy-cock" , "Dandy-hen" , "Dare-devil" , "Database" , "Daughter-in-law" ,
        "Day-coal" , "Day-dreamed" , "Day-labor" , "Day-laborer" , "Day-net" , "Day-peep" , "Day-star" , "Daybed" , "Daybook" , "Daybreak" , "Daydream" , "Daylight" , "Daytime" , "De-differentiation" , "De-stocking" ,
        "Dead" , "Dead-eye" , "Dead-pay" , "Dead-reckoning" , "Dead-wood" , "Deadend" , "Deadline" , "Deadlock" , "Deaf-mutism" , "Death's-head" , "Death's-herb" , "Decoy-duck" , "Decoy-man" , "Deer's-tongue" ,
        "Deer-neck" , "Demi-island" , "Demi-rilievo" , "Derring-do" , "Desktop" , "Deus-ex-machina" , "Devil-diver" , "Dew-point" , "Diamond-back" , "Diary" , "Die-hard" , "Die-off" , "Diner-out" , "Dining-room" ,
        "Director-general" , "Directors-general" , "Disc-jockey" , "Disciple-ship" , "Dishcloth" , "Dishpan" , "Dishwasher" , "Dishwater" , "Disk" , "Diskdrive" , "Ditty-bag" , "Ditty-box" , "Divi-divi" , "Do-all" ,
        "Do-gooders" , "Do-little" , "Do-naught" , "Do-nothing" , "Do-nothingism" , "Do-nothingness" , "Dock-cress" , "Dog's-bane" , "Dog's-ear" , "Dog's-tail grass" , "Dog's-tongue" , "Dog-brier" , "Dog-fox" ,
        "Dog-rose" , "Dogwood" , "Doll-like" , "Don't-knows" , "Doorbell" , "Doorknob" , "Doorstop" , "Double-bass" , "Double-dealing" , "Double-decker" , "Double-ender" , "Double-entendre" , "Double-fault" ,
        "Double-quick" , "Double-ripper" , "Double-tongue" , "Double-tonguing" , "Dousing-chock" , "Dove's-foot" , "Down-cycle" , "Down-graded" , "Down-grading" , "Down-payment" , "Down-payments" , "Down-pour" ,
        "Down-share" , "Down-side" , "Down-spout" , "Down-trend" , "Down-turn" , "Down-wind" , "Downbeat" , "Downfall" , "Downpour" , "Downstairs" , "Downturn" , "Downunder" , "Drabble-tail" , "Draggle-tail" ,
        "Drastic" , "Draw-cut" , "Drawback" , "Drawbridge" , "Drawing-room" , "Dressing-up" , "Dressmaker" , "Drive-in" , "Driveway" , "Drop-in" , "Drop-off" , "Dropout" , "Drugstore" , "Drumstick" , "Dry-cleaners" ,
        "Dry-rubbing" , "Dry-run" , "Duck's-foot" , "Duck's-meat" , "Duckbill" , "Duckpin" , "Duckweed" , "Dugout" , "Dumb-bell" , "Dumb-show" , "Dumb-waiter" , "Durable-goods" , "Dust-point" , "E-la" , "E-mail" ,
        "E-mailing" , "Ear-piercer" , "Ear-shell" , "Earache" , "Eardrop" , "Eardrum" , "Earphone" , "Earring" , "Earth-tongue" , "Earthbound" , "Earthquake" , "Earthward" , "Earthwork" , "Earthworm" , "Earwig" ,
        "Easy-chair" , "Easygoing" , "Echo-location" , "Eddy-current" , "Editor-in-chief" , "Eel-mother" , "Egg-bird" , "Egg-cup" , "Egg-glass" , "Egghead" , "Eggshell" , "Electro-ballistics" , "Electro-biologist" ,
        "Electro-biology" , "Electro-bioscopy" , "Electro-capillarity" , "Electro-chemistry" , "Electro-chronograph" , "Electro-dynamics" , "Electro-dynamometer" , "Electro-engraving" , "Electro-etching" ,
        "Electro-gilding" , "Electro-kinetics" , "Electro-magnet" , "Electro-magnetism" , "Electro-metallurgy" , "Electro-motion" , "Electro-negative" , "Electro-physiology" , "Electro-positive" ,
        "Electro-puncturation" , "Electro-puncture" , "Electro-puncturing" , "Electro-stereotype" , "Electro-telegraphy" , "Electro-therapeutics" , "Electro-thermancy" , "Electro-tint" , "Electro-vitalism" ,
        "Elsewhere" , "Ember-goose" , "End-all" , "End-on" , "End-to-end" , "End-user" , "Evergreen" , "Everybody" , "Everyday" , "Everyone" , "Everything" , "Everywhere" , "Ex-president" , "Ex-presidents" ,
        "Ex-voto" , "Excito-motion" , "Extracurricular" , "Eye-appeal" , "Eye-catching" , "Eye-saint" , "Eye-splice" , "Eye-spot" , "Eyeball" , "Eyeballs" , "Eyebrow" , "Eyecatching" , "Eyeglasses" , "Eyelash" ,
        "Eyelid" , "Eyesight" , "Eyewitness" , "Face-down" , "Face-off" , "Face-on" , "Face-saving" , "Factoring-in" , "Fade-in" , "Fade-out" , "Fair-leader" , "Fair-world" , "Fall-out" , "Fantastic-alness" ,
        "Far-away" , "Farding-bag" , "Farmhouse" , "Fashion-monger" , "Fast-day" , "Father-in-law" , "Father-lasher" , "Fatherhood" , "Fatherland" , "Fault-finder" , "Fault-finding" , "Fausse-braye" ,
        "Feather-edge/" , "Feather-few/" , "Feather-foil" , "Feather-head" , "Fee-faw-fum" , "Feedback" , "Fellow-commoner" , "Fellow-creature" , "Fellow-feeling" , "Felo-de-se" , "Fenes-tella" ,
        "Fer-de-lance" , "Ferret-eye" , "Festi-val" , "Field-worker" , "Fig-shell" , "Figure-eight" , "Fill-in" , "Fill-up" , "Film noir" , "Film-maker" , "Filmmaker" , "Finger-printed" , "Fingernail" ,
        "Fingerprint" , "Fingle-fangle" , "Fire-eater" , "Fire-engine" , "Fire-set" , "Firearm" , "Fireball" , "Fireboat" , "Firebomb" , "Firebreak" , "Firecracker" , "Firefighter" , "Fireflies" , "Firefly" ,
        "Firehouse" , "Fireman" , "Fireplace" , "Fireproof" , "Firewater" , "Firewood" , "Firework" , "Fireworks" , "Firmer-chisel" , "First-rate" , "Fish-block" , "Fish-tackle" , "Fishbowl" , "Fisherman" ,
        "Fisheye" , "Fishhook" , "Fishlike" , "Fishmonger" , "Fishnet" , "Fishpond" , "Fishtail" , "Five-finger" , "Five-leaf" , "Five-twenties" , "Flag-waver" , "Flag-wavers" , "Flag-waving" , "Flash-bulb" ,
        "Flashback" , "Flashlight" , "Flat-cap" , "Flax-plant" , "Flea-beetle" , "Flea-bite" , "Flea-louse" , "Fleur-de-lis" , "Flight-shot" , "Flip-flap" , "Flip-flop" , "Flip-flopped" , "Flip-flopping" ,
        "Flirt-gill" , "Floodlight" , "Floppy" , "Flos-ferri" , "Flowchart" , "Flower-de-luce" , "Flower-fence" , "Flower-gentle" , "Flowerpot" , "Fly-by" , "Fly-case" , "Fly-in" , "Foddle-faddle" , "Folklore" ,
        "Follow-through" , "Follow-up" , "Follow-ups" , "Food-stuffs" , "Fool-largesse" , "Foot-up" , "Football" , "Foothill" , "Footlights" , "Footlocker" , "Footman" , "Footnote" , "Footprint" , "Footprints" ,
        "Footrest" , "Footstep" , "Fop-doodle" , "Forbearer" , "Forbid" , "Fore-night" , "Fore-runner" , "Fore-topmast" , "Fore-topsail" , "Forearm" , "Forebear" , "Forebrain" , "Forecast" , "Forecastle" ,
        "Foreclose" , "Foreclosure" , "Foredoom" , "Forefather" , "Forefeet" , "Forefinger" , "Forefoot" , "Forego" , "Foregone" , "Foreground" , "Forehand" , "Forehead" , "Foreknowledge" , "Foreleg" ,
        "Foreman" , "Foremost" , "Forepaws" , "Foresee" , "Foreshadow" , "Foresight" , "Forestall" , "Foretaste" , "Forethought" , "Foretold" , "Forever" , "Forewarn" , "Foreword" , "Forget" ,
        "Forget-me-not" , "Forget-me-nots" , "Forgive" , "Forklift" , "Format" , "Fortnight" , "Forty-spot" , "Foster-brother" , "Foul-up" , "Four-in-hand" , "Four-o'clock" , "Four-poster" ,
        "Four-wheeler" , "Four-wheelers" , "Frank-chase" , "Frank-fee" , "Frank-law" , "Frank-marriage" , "Free-association" , "Free-for-all" , "Free-kick" , "Free-kicks" , "Free-lance" , "Free-liver" ,
        "Free-living" , "Free-love" , "Free-lover" , "Free-martin" , "Free-on-board" , "Free-ride" , "Free-trade" , "Free-traders" , "Free-wheeled" , "Free-zone" , "Freelance" , "Freeway" , "Freshwater" ,
        "Friendship" , "Frogs-bit" , "Front-runner" , "Frost-blite" , "Frostbite" , "Fruitcake" , "Fruitcup" , "Full-back" , "Full-backs" , "Full-house" , "Full-tilt" , "Full-timers" , "G-string" ,
        "Gaber-lunzie" , "Gaff-topsail" , "Galacta-gogue" , "Gale-opithecus" , "Galley-bird" , "Galley-worm" , "Gang-flower" , "Gas-burner" , "Gasworks" , "Gatecrasher" , "Gaud-day" , "Gauger-ship" ,
        "Gear-up" , "Gearshift" , "Gelder-rose" , "Gems-horn" , "Genetic-engineering" , "Gentile-falcon" , "Gentlemen" , "Get-go" , "Get-out" , "Get-penny" , "Get-together" , "Get-togethers" ,
        "Get-up" , "Getaway" , "Ghost-town" , "Ghostwriter" , "Gib-cat" , "Giddy-head" , "Gier-eagle" , "Gier-falcon" , "Gill-flirt" , "Gingerbread" , "Ginny-carriage" , "Girlfriend" , "Give-and-take" ,
        "Give-aways" , "Give-up" , "Give-ups" , "Glass-crab" , "Glass-rope" , "Glass-snail" , "Glass-snake" , "Glass-sponge" , "Glassmaking" , "Go-ahead" , "Go-around" , "Go-between" , "Go-by" , "Go-cart" ,
        "Go-getting" , "Go-out" , "Go-slow" , "Go-slows" , "Goalkeeper" , "Gode-year" , "Godfather" , "Goggle-eye" , "Going-away" , "Going-over" , "Goings-on" , "Gold-beating" , "Gold-hammer" , "Golden-eye" ,
        "Golden-rod" , "Goldfish" , "Goloe-shoe" , "Good-by" , "Good-bye" , "Good-day" , "Good-fellowship" , "Good-night" , "Goodbye" , "Goodlooking" , "Goodnight" , "Goody-goody" , "Gor-belly" , "Governors-general" ,
        "Grandaunt" , "Grandchild" , "Grandchildren" , "Granddaughter" , "Grandfather" , "Grandmother" , "Grandnephew" , "Grandnieces" , "Grandparent" , "Grandson" , "Grandstand" , "Granduncle" , "Grant-in-aid" ,
        "Grants-in-aid" , "Grapefruit" , "Grasshopper" , "Grassland" , "Gravel-stone" , "Graveyard" , "Great-aunt" , "Great-grandchild" , "Great-granddaughter" , "Great-grandfather" , "Great-grandmother" ,
        "Great-grandson" , "Great-grandsons" , "Great-heartedness" , "Great-nephew" , "Greedy-gut" , "Green-broom" , "Green-leek" , "Green-stall" , "Greenhouse" , "Gridlock" , "Grotto-work" , "Ground-floor" ,
        "Groundwater" , "Grownup" , "Grub-up" , "Guidebook" , "Guideline" , "Gumball" , "Gun-carriage" , "Gunboat" , "Gunfire" , "Gunmetal" , "Gunpowder" , "Gutta-percha" , "Ha-ha" , "Ha-has" , "Hag-taper" ,
        "Hail-fellow" , "Hair-salt" , "Haircut" , "Hairdresser" , "Hake's-dame" , "Half-and-half" , "Half-asleep" , "Half-back" , "Half-board" , "Half-boot" , "Half-bound" , "Half-breed" , "Half-brother" ,
        "Half-caste" , "Half-deck" , "Half-fish" , "Half-formed" , "Half-jokingly" , "Half-length" , "Half-mast" , "Half-moon" , "Half-pike" , "Half-port" , "Half-ray" , "Half-sister" , "Half-slip" , "Half-sword" ,
        "Half-tounue" , "Half-wit" , "Hall-mark" , "Halter-sack" , "Hamburger" , "Hammer-beam" , "Hammerhead" , "Hand brake" , "Hand luggage" , "Hand-hole" , "Hand-in-hand" , "Hand-me-down" , "Hand-me-downs" ,
        "Hand-off" , "Hand-out" , "Hand-over" , "Hand-work" , "Handbag" , "Handball" , "Handbook" , "Handcuff" , "Handgun" , "Handi-craftsman" , "Handing-in" , "Handlebar" , "Handmade" , "Handout" , "Handshake" ,
        "Handwriting" , "Handyy-dandy" , "Hang-by" , "Hang-fire" , "Hang-glider" , "Hang-gliders" , "Hang-gliding" , "Hang-up" , "Hang-ups" , "Hanger-on" , "Hangers-on" , "Hankey-pankey" , "Hara-kiri" , "Hard-board" ,
        "Hard-liner" , "Hard-liners" , "Hard-on" , "Hard-ons" , "Hard-ships" , "Hard-standing" , "Hard-tack" , "Hard-wiring" , "Hare's-ear" , "Hare's-tail" , "Hart's-ear" , "Hart-tongue" , "Harvest-home" , "Has-beens" ,
        "Hasty-pudding" , "Hat-trick" , "Hatch-boat" , "Hatti-sherif" , "Have-not" , "Haw-haw" , "Hay-cutter" , "Haystack" , "He" , "Head-cheese" , "Head-hunter" , "Head-long" , "Head-over-heels" , "Head-room" ,
        "Head-up" , "Headache" , "Headdress" , "Headland" , "Headlight" , "Headline" , "Headphones" , "Headquarter" , "Headquarters" , "Headset" , "Headstone" , "Headway" , "Heart's-ease" , "Heart-attack" ,
        "Heart-spoon" , "Heart-throb" , "Heartbeat" , "Heartwarming" , "Heave-ho" , "Heddle-eye" , "Heir-apparent" , "Heir-at-law" , "Hell-cat" , "Hell-diver" , "Hemi-demi-semiquaver" , "Hen's-foot" , "Hepato-pancreas" ,
        "Herb-woman" , "Here-and-now" , "Hereafter" , "Hereby" , "Herein" , "Hereupon" , "Herewith" , "Herringbone" , "Herself" , "Hi-fi" , "Hiberno-" , "Celtic" , "Hide-away" , "Hig-taper" , "High-churchism" ,
        "High-churchman" , "High-churchman-ship" , "High-flyer" , "High-go" , "High-hoe" , "High-holder" , "High-low" , "High-mindedness" , "High-priesthood" , "High-priestship" , "High-stepper" , "High-tech" ,
        "Highball" , "Highchair" , "Higher-up" , "Highland" , "Highlands" , "Highway" , "Hilltop" , "Himself" , "Hiving-off" , "Ho-hum" , "Hog's-back" , "Hogger-pump" , "Holder-forth" , "Holdup" , "Hole-in-one" ,
        "Home-coming" , "Home-keeping" , "Home-runs" , "Home-speaking" , "Homemade" , "Homeowner" , "Homesick" , "Hometown" , "Homework" , "Honey-bag" , "Honeybee" , "Honeycomb" , "Honeydew" , "Honeymoon" ,
        "Honeysuckle" , "Hoodman-blind" , "Hook-up" , "Hookup" , "Hookworm" , "Hop-o'-my-thumb" , "Hop-thumb" , "Horse-chestnut" , "Horse-drench" , "Horse-jockey" , "Horse-leech" , "Horse-leechery" ,
        "Horse-litter" , "Horse-radish" , "Horseback" , "Horsefly" , "Horsehair" , "Horseman" , "Horseplay" , "Horsepower" , "Horseradish" , "Hostess-ship" , "Hot-bed" , "Hot-footed" , "Hot-head" ,
        "Hot-heads" , "Hot-house" , "Hot-line" , "Hotel-de-ville" , "Hotel-" , "Dieu" , "Hound's-tongue" , "Hourglass" , "Houseboat" , "Household" , "Housekeeper" , "Housetop" , "Housework" , "Hover-hawk" ,
        "However" , "Hubble-bubble" , "Hugger-mugger" , "Human-being" , "Hundred-weight" , "Hunt's-up" , "Hunt-counter" , "Hurdy-gurdy" , "Hurly-burly" , "Huron-" , "Iroquous" , "Hydro-extractor" ,
        "Hyper-inflationary" , "Iceberg" , "Icebox" , "Icebreaker" , "Ideo-motion" , "Ihlang-ihlang" , "Ill-wisher" , "Imber-goose" , "Imp-pole" , "In-and-in" , "In-between" , "In-breeding" , "In-comers" ,
        "In-crowd" , "In-equality" , "In-fighting" , "In-flow" , "In-flows" , "In-gathering" , "In-going" , "In-jokes" , "In-juries" , "In-law" , "In-migrants" , "In-patient" , "In-patients" , "In-put" ,
        "In-road" , "In-roads" , "In-swinger" , "In-take" , "In-the-money" , "Inchworm" , "Income" , "Indoor" , "Indoors" , "Infield" , "Inland" , "Inlet" , "Inner-city" , "Innkeeper" , "Input" , "Inside" ,
        "Instep" , "Intake" , "Inter-action" , "Inter-company" , "Inter-dependence" , "Inter-marriage" , "Inter-play" , "Inter-relation" , "Into" , "Iron-gray" , "Ironwork" , "Itself" , "Ivory-bill" ,
        "Jack-a-dandy" , "Jack-a-lent" , "Jack-in-the-box" , "Jack-o'-lantern" , "Jackknife" , "Jackpot" , "Jackrabbit" , "Jailbait" , "Jane-of-apes" , "Jar-owl" , "Jawbone" , "Jaywalk" , "Jellybean" ,
        "Jellyfish" , "Jetliner" , "Jetport" , "Jew's-ear" , "Jew's-harp" , "Jew's-stone" , "Jigsaw" , "Jill-flirt" , "Jim-crow" , "John's-wort" , "Joint-fir" , "Jolly-boat" , "Joystick" , "July-flower" ,
        "Jumble-sale" , "Jump-off" , "Jump-started" , "Jumpshot" , "Jumpsuit" , "Jura-trias" , "Keepsake" , "Keffe-kil" , "Keilhau-ite" , "Kettledrum" , "Keyboard" , "Keyhole" , "Keynote" , "Keypad" ,
        "Keypunch" , "Keystone" , "Keystroke" , "Keyway" , "Keyword" , "Kick-off" , "Kickball" , "Kickoff" , "Kicksy-wicksy" , "Kicky-wisky" , "Kill-joy" , "Killjoy" , "Kilowatt-hour" , "Kind-heartedness" ,
        "Kindhearted" , "King-post" , "Kiss-off" , "Kitchen-ry" , "Kneecap" , "Knees-up" , "Knife-edge" , "Knight-errant" , "Knight-errantry" , "Knighthood" , "Knock-knee" , "Knock-off" , "Knothole" ,
        "Know-all" , "Know-alls" , "Know-how" , "Know-nothing" , "Know-nothingism" , "Knucklehead" , "Kohl-rabi" , "Lace-bark" , "Ladies-in-waiting" , "Lady-in-waiting" , "Lady-killer" , "Lady-killing" ,
        "Ladybug" , "Lake-dweller" , "Lamb's-quarters" , "Lamp-post" , "Landlord" , "Landmark" , "Landslip" , "Lark's-heel" , "Lash-up" , "Late-comer" , "Law-breaking" , "Law-fall" , "Law-maker" , "Lawsuit" ,
        "Lay-by" , "Lay-up" , "Layoff" , "Layout" , "Lead-in" , "Leaf-nosed" , "Lean-to" , "Leapfrog" , "Leave-taking" , "Left-handedness" , "Left-handiness" , "Left-wing" , "Leftover" , "Leftovers" , "Leg-up" ,
        "Lenni-" , "Lenape" , "Lese-majesty" , "Let-down" , "Let-downs" , "Letterhead" , "Lick-spigot" , "Lick-spittle" , "Lie-in" , "Life-cycle" , "Life-preserver" , "Lifeblood" , "Lifeboat" , "Lifeguard" ,
        "Lifelike" , "Lifeline" , "Lifelong" , "Lifesaver" , "Lifestyle" , "Lifetime" , "Lifework" , "Lift-off" , "Light-boat" , "Light-horseman" , "Light-o'-love" , "Light-ship" , "Lightheaded" , "Lighthouse" ,
        "Lights-out" , "Lightweight" , "Lign-aloes" , "Lignum-vitae" , "Lilly-pilly" , "Limelight" , "Limestone" , "Line-of-sight" , "Line-up" , "Ling-bird" , "Link-up" , "Linsey-woolsey" , "Lion-heart" , "Lipstick" ,
        "Little-ease" , "Live-bearer" , "Live-forever" , "Living-room" , "Loanshark" , "Lock-down" , "Lock-in" , "Lock-set" , "Lock-weir" , "Locked-jaw" , "Locking-in" , "Lode-ship" , "Log-chip" , "Log-in" , "Log-on" ,
        "Log-ship" , "Lombar-house" , "Lombard-house" , "Long-haired" , "Long-house" , "Long-sight" , "Long-sightedness" , "Long-stop" , "Long-sufferance" , "Long-tongue" , "Long-waves" , "Longhand" , "Longhouse" ,
        "Longshoremen" , "Look-alike" , "Look-in" , "Look-up" , "Looker-on" , "Looking-glass" , "Lookout" , "Loom-gale" , "Loophole" , "Lotos-eater" , "Lotus-eater" , "Loudspeaker" , "Loup-cervier" , "Loup-loup" ,
        "Love-child" , "Love-drury" , "Love-in" , "Love-in-a-mists" , "Love-making" , "Love-sickness" , "Lovebird" , "Loving-kindness" , "Low-churchism" , "Low-churchman" , "Low-churchmanship" , "Low-mindedness" ,
        "Lukewarm" , "Lying-in" , "Lynch-pin" , "Macro-chemistry" , "Macro-economic" , "Mad-apple" , "Maggot-pie" , "Magneto-electricity" , "Magot-pie" , "Mahl-stick" , "Mail-bag" , "Mail-shell" , "Mailbox" ,
        "Main-gauche" , "Main-hamper" , "Mainland" , "Mainline" , "Major-domo" , "Major-general" , "Major-leaguer" , "Make-belief" , "Make-believe" , "Make-do" , "Make-game" , "Make-peace" , "Make-up" ,
        "Making-iron" , "Making-up" , "Male-odor" , "Man-about-town" , "Man-at-arms" , "Man-eater" , "Man-in-the-street" , "Man-of-war" , "Mangel-wurzel" , "Manhandle" , "Manhole" , "Manhunt" , "Mar-text" ,
        "March-ward" , "Mare's-nest" , "Mare's-tail" , "Mark-down" , "Mark-up" , "Mary-bud" , "Mastermind" , "Match-cloth" , "Match-coat" , "Matchbox" , "Maul-stick" , "Meals-on-wheels" , "Meantime" , "Meanwhile" ,
        "Meeting" , "Melt-water" , "Men-at-arms" , "Men-of-war" , "Men-pleaser" , "Merry-andrew" , "Merry-go-round" , "Merry-go-rounds" , "Merry-makers" , "Mezzo-relievo" , "Mezzo-rilievo" , "Mezzo-soprano" ,
        "Micro-chemistry" , "Micro-economic" , "Micro-geology" , "Mid-afternoon" , "Mid-air" , "Mid-day" , "Mid-field" , "Mid-fielder" , "Mid-line" , "Mid-morning" , "Mid-off" , "Mid-on" , "Mid-point" ,
        "Mid-stream" , "Mid-summer" , "Mid-way" , "Mid-week" , "Mid-winter" , "Mid-year" , "Middle-earth" , "Middle-ground" , "Middleman" , "Mill-cake" , "Mill-sixpence" , "Mince-meat" , "Mingle-mangle" ,
        "Mini-buses" , "Mini-car" , "Mini-computers" , "Mini-cycle" , "Mini-series" , "Mini-skirted" , "Mini-skirts" , "Mini-state" , "Mini-states" , "Mini-summit" , "Mini-tour" , "Mini-van" , "Mini-vans" ,
        "Minister-without-portfoli" , "Mint-master" , "Minute-jack" , "Mis-adaptation" , "Mis-assessment" , "Mis-direction" , "Mis-spent" , "Mischief-maker" , "Mischief-making" , "Mix-up" , "Mock-up" ,
        "Molly-mawk" , "Money-maker" , "Money-making" , "Monkey-bread" , "Monkey-cup" , "Monkey-pot" , "Mono-cultural" , "Monte-acid" , "Moon-eye" , "Moon-rock" , "Moonbeam" , "Moonlight" , "Moonlit" ,
        "Moonscape" , "Moonshine" , "Moonstruck" , "Moonwalk" , "Moot-hall" , "Moot-hill" , "Moot-house" , "Moreover" , "Morning-glory" , "Morris-pike" , "Mothball" , "Mother-in-law" , "Mother-of-pearl" ,
        "Mother-of-thyme" , "Motherhood" , "Motorcycle" , "Mouse-ear" , "Mule-jenny" , "Multi-dimensional" , "Multi-media" , "Multi-million" , "Multi-millionaire" , "Multi-millionaires" , "Multi-millions" ,
        "Multi-national" , "Multi-nationals" , "Multi-processor" , "Mum-chance" , "Mumbo-jumbo" , "Mute-hill" , "Muzzle-loader" , "Myself" , "Namby-pamby" , "Nap-taking" , "Nape-crest" , "Nationwide" ,
        "Navel-string" , "Nearby" , "Neb-neb" , "Neighborhood" , "Neo-" , "Christianity" , "Neo-fascism" , "Neo-nazi" , "Nervous-systems" , "Network" , "Nevermore" , "Nevertheless" , "New-comer" , "Newborn" ,
        "Newfound" , "Newly-weds" , "News agency" , "News-book" , "News-letter" , "News-vnder" , "News-writer" , "Newsagent" , "Newsboy" , "Newsbreak" , "Newscast" , "Newscaster" , "Newsdealer" , "Newsflash" ,
        "Newsletter" , "Newsman" , "Newspaper" , "Newsperson" , "Newsprint" , "Newsreader" , "Newsreel" , "Newsroom" , "Newsstand" , "Newsworthy" , "Next-door" , "Next-of-kin" , "Nightcap" , "Nightclub" ,
        "Nightfall" , "Nightgown" , "Nightmare" , "Nine-bark" , "Nine-eyes" , "Nine-killer" , "Nine-pins" , "Nitro-chloroform" , "Nitty-gritty" , "No-ball" , "No-hoper" , "No-hopers" , "No-mans-land" ,
        "No-no" , "No-one" , "No-show" , "Nobody" , "Noisemaker" , "Noli-me-tangere" , "Non-acceptance" , "Non-alignment" , "Non-application" , "Non-arrivals" , "Non-attendance" , "Non-bank" , "Non-banks" ,
        "Non-being" , "Non-binding" , "Non-breeders" , "Non-business" , "Non-citizens" , "Non-co-operation" , "Non-combatants" , "Non-communication" , "Non-completion" , "Non-compliance" , "Non-confidence" ,
        "Non-confirmation" , "Non-conformances" , "Non-conformity" , "Non-contributors" , "Non-cooperation" , "Non-deliveries" , "Non-delivery" , "Non-determination" , "Non-disclosure" , "Non-disclosures" ,
        "Non-discrimination" , "Non-drinkers" , "Non-ego" , "Non-emergence" , "Non-entry" , "Non-event" , "Non-executive" , "Non-executives" , "Non-existence" , "Non-existent" , "Non-experts" , "Non-feasance" ,
        "Non-fiction" , "Non-food" , "Non-interference" , "Non-intervention" , "Non-issue" , "Non-jew" , "Non-lawyers" , "Non-liability" , "Non-life" , "Non-linearities" , "Non-linearity" , "Non-member" ,
        "Non-members" , "Non-membership" , "Non-metals" , "Non-neutrality" , "Non-observance" , "Non-occupation" , "Non-owners" , "Non-participants" , "Non-participation" , "Non-parties" , "Non-party" ,
        "Non-payment" , "Non-payments" , "Non-performance" , "Non-players" , "Non-producers" , "Non-proliferation" , "Non-prossing" , "Non-publication" , "Non-ratification" , "Non-receipt" , "Non-recognition" ,
        "Non-registration" , "Non-rejection" , "Non-renewal" , "Non-replacement" , "Non-revision" , "Non-segregation" , "Non-selection" , "Non-shareholders" , "Non-smoker" , "Non-smokers" , "Non-socialist" ,
        "Non-solicitation" , "Non-solidarity" , "Non-solvent" , "Non-specificity" , "Non-starter" , "Non-strikers" , "Non-tax" , "Non-traders" , "Non-uniformity" , "Non-users" , "Non-violence" , "Non-voting" ,
        "Non-white" , "Non-whites" , "Non-winner" , "Non-word" , "Non-words" , "Non-workers" , "Noon-flower" , "Nor-wester" , "North-east" , "North-eastwards" , "North-west" , "North-westwards" , "Northeast" ,
        "Nosy-parker" , "Notebook" , "Noteworthy" , "Nothing" , "Nouveau-riche" , "Nowhere" , "Nursemaid" , "Nutcracker" , "O-clock" , "O-ring" , "Oatmeal" , "Off-licence" , "Off-licences" , "Off-season" ,
        "Off-track" , "Off-year" , "Offspring" , "Old-guard" , "Old-maidism" , "Old-stagers" , "Old-style" , "Old-timers" , "Olla-podrida" , "Omnium-gatherum" , "On-hanger" , "On-looker" , "On-market" ,
        "On-off" , "On-ramps" , "On-road" , "On-stage" , "On-stream" , "On-the-cards" , "Once-over" , "Oncoming" , "One-step" , "Oneself" , "Onetime" , "Ongoing" , "Online" , "Onlooker" , "Onto" , "Orang-outang" ,
        "Oso-berry" , "Oueen-post" , "Ourang-outang" , "Ourselves" , "Out-of-towner" , "Out-of-towners" , "Out-patient" , "Out-put" , "Out-takes" , "Outbreak" , "Outburst" , "Outcome" , "Outcry" , "Outdoor" ,
        "Outfield" , "Outfit" , "Outgoing" , "Outhouse" , "Outlaw" , "Outlay" , "Outlet" , "Outline" , "Outlook" , "Output" , "Outset" , "Outside" , "Outskirts" , "Outsource" , "Outstanding" , "Outstretched" ,
        "Over-abundance" , "Over-adjustment" , "Over-application" , "Over-appreciation" , "Over-apprehension" , "Over-assessment" , "Over-attachment" , "Over-capacities" , "Over-capacity" , "Over-caution" ,
        "Over-compensation" , "Over-complexity" , "Over-concentration" , "Over-consideration" , "Over-consumption" , "Over-contributions" , "Over-correction" , "Over-cultivation" , "Over-decoration" ,
        "Over-dependence" , "Over-distortion" , "Over-doses" , "Over-emphases" , "Over-emphasis" , "Over-emphatic" , "Over-employment" , "Over-enthusiasm" , "Over-exaggeration" , "Over-expansion" ,
        "Over-expenditure" , "Over-exploitation" , "Over-exposure" , "Over-extraction" , "Over-exuberance" , "Over-familiarity" , "Over-garment" , "Over-generosity" , "Over-heavily" , "Over-identification" ,
        "Over-importation" , "Over-indebtedness" , "Over-indexing" , "Over-insistence" , "Over-investment" , "Over-manning" , "Over-optimism" , "Over-production" , "Over-protection" , "Over-provision" ,
        "Over-regulation" , "Over-reliance" , "Over-reporting" , "Over-representative" , "Over-restriction" , "Over-retention" , "Over-saturation" , "Over-secretion" , "Over-speculation" , "Over-story" ,
        "Over-supply" , "Over-the-top" , "Over-view" , "Over-voltage" , "Overabundance" , "Overacting" , "Overall" , "Overalls" , "Overbalancing" , "Overbearing" , "Overboard" , "Overcoat" , "Overcome" ,
        "Overdo" , "Overdressed" , "Overexposure" , "Overflow" , "Overfull" , "Overhanging" , "Overhead" , "Overkill" , "Overland" , "Overleaf" , "Overload" , "Overlook" , "Overpass" , "Overseas" ,
        "Overseer" , "Overshoe" , "Overshoes" , "Overstatement" , "Overtake" , "Overtaxed" , "Overtime" , "Overturned" , "Overuse" , "Overvalued" , "Overweight" , "Overworking" , "Oyster-green" ,
        "Pacemaker" , "Packed-up" , "Painkiller" , "Pall-mall" , "Pancake" , "Paperback" , "Paperwork" , "Papier-mache" , "Parrot's-bill" , "Pass-key" , "Pass-parole" , "Pass-through" , "Passbook" ,
        "Passer-by" , "Passkey" , "Passover" , "Passport" , "Password" , "Paste-up" , "Pay-as-you-go" , "Paycheck" , "Payoff" , "Payroll" , "Pea-jacket" , "Peace-keeping" , "Peanuts" , "Peep-hole" ,
        "Pell-mell" , "Penknife" , "Penny-a-liner" , "Penny-pinching" , "Peppermint" , "Percent" , "Petro-dollar" , "Phase-down" , "Phase-in" , "Phasing-in" , "Phone-in" , "Phosphor-bronze" , "Photo-electrotype" ,
        "Photo-engraving" , "Photo-epinasty" , "Physico-mathematics" , "Physico-philosophy" , "Physico-theology" , "Pick-fault" , "Pick-me-up" , "Pickle-herring" , "Pickpocket" , "Pickup" , "Pig-iron" ,
        "Pig-sticking" , "Pigtail" , "Pike-devant" , "Pile-up" , "Pill-willet" , "Pillar-block" , "Pilled-garlic" , "Pinball" , "Pince-nez" , "Pincushion" , "Pinhole" , "Pinstripe" , "Pinup" , "Pinwheel" ,
        "Pit-hole" , "Pitch-ore" , "Plank-sheer" , "Plant-cane" , "Play-off" , "Play-on" , "Playback" , "Playboy" , "Played-on" , "Playground" , "Playhouse" , "Playing-off" , "Playmate" , "Plaything" ,
        "Playthings" , "Plus-four" , "Pock-marked" , "Pock-marks" , "Pock-pudding" , "Pocketknife" , "Point-of-no-return" , "Point-to-point" , "Point-to-points" , "Poking-stick" , "Pole-axed" , "Policeman" ,
        "Policewoman" , "Policy-makers" , "Policy-making" , "Poly-mountain" , "Pom-pom" , "Ponytail" , "Poor-john" , "Poor-will" , "Poor-willie" , "Popcorn" , "Port-of-call" , "Port-royalist" , "Porte-cochere" ,
        "Post-abdomen" , "Post-captain" , "Post-coital" , "Post-debate" , "Post-disseizin" , "Post-disseizor" , "Post-election" , "Post-fine" , "Post-season" , "Post-temporal" , "Post-tragus" , "Postcard" ,
        "Postman" , "Postmark" , "Postmaster" , "Postmaster-general" , "Postoffice" , "Pot-bellied" , "Pot-belly" , "Pot-walloper" , "Pothole" , "Pouch-shell" , "Pound-breach" , "Power-play" , "Powers-that-be" ,
        "Praise-meeting" , "Pre-adaptation" , "Pre-announcement" , "Pre-approval" , "Pre-booking" , "Pre-commitment" , "Pre-condition" , "Pre-conditions" , "Pre-construction" , "Pre-cursor" , "Pre-dawn" ,
        "Pre-destination" , "Pre-disposition" , "Pre-election" , "Pre-emergency" , "Pre-eminence" , "Pre-emption" , "Pre-exposure" , "Pre-filter" , "Pre-financing" , "Pre-fixing" , "Pre-history" , "Pre-inspection" ,
        "Pre-judging" , "Pre-knowledge" , "Pre-labelled" , "Pre-lunch" , "Pre-market" , "Pre-marketed" , "Pre-marketing" , "Pre-occupation" , "Pre-occupations" , "Pre-orders" , "Pre-planning" , "Pre-processing" ,
        "Pre-production" , "Pre-raphaelite" , "Pre-registered" , "Pre-release" , "Pre-sale" , "Pre-sales" , "Pre-scheduled" , "Pre-schooler" , "Pre-stocked" , "Pre-testing" , "Pre-training" , "Pre-trial" ,
        "Pre-verification" , "President-elect" , "Press-up" , "Pricking-up" , "Printout" , "Prisoner-of-war" , "Prittle-prattle" , "Profit-taking" , "Prompt-book" , "Prompt-note" , "Prong-hoe" , "Proofread" ,
        "Prospect" , "Pseudo-bulb" , "Pseudo-china" , "Pseudo-cone" , "Pseudo-cumene" , "Pseudo-dipteral" , "Pseudo-galena" , "Pseudo-heart" , "Pseudo-symmetry" , "Pseuso-peripteral" , "Psitta-co-fulvine" ,
        "Public-school" , "Public-sector" , "Puddle-ball" , "Puddle-bar" , "Puff-leg" , "Puff-up" , "Pull-in" , "Pull-on" , "Push-pull" , "Put-down" , "Put-downs" , "Put-off" , "Put-put" , "Putter-on" , "Qua-bird" ,
        "Quarrelsome" , "Quarry-man" , "Quarter-deck" , "Quarter-point" , "Quarterback" , "Quartermaster" , "Quater-cousin" , "Question-mark" , "Quick-fix" , "Quick-wittedness" , "Quicksand" , "Quicksilver" ,
        "Rabble-rout" , "Racehorse" , "Rack-rent" , "Rack-renter" , "Racket-tail" , "Racquetball" , "Radio-flagellata" , "Railroad" , "Railway" , "Rainbow" , "Raincheck" , "Raincoat" , "Raindrop" , "Rainstorm" ,
        "Rainwater" , "Rake-vein" , "Ramble" , "Rank-and-file" , "Raree-show" , "Rat-tail" , "Rattlesnake" , "Rattletrap" , "Raven's-duck" , "Rawhide" , "Re-audit" , "Re-creation" , "Re-demption" , "Re-drafted" ,
        "Re-election" , "Re-entry" , "Re-formation" , "Re-forming" , "Re-iced" , "Re-nomination" , "Re-presentation" , "Re-routing" , "Re-stacked" , "Re-turfed" , "Re-voted" , "Read-out" , "Read-through" ,
        "Ready-mix" , "Ready-mixed" , "Ready-to-wear" , "Real-estate" , "Rear-horse" , "Receivership" , "Red-gum" , "Red-riband" , "Red-tapism" , "Red-tapist" , "Redhead" , "Redwood" , "Reed-mace" , "Reef-band" ,
        "Remainder-man" , "Rent-a-car" , "Rep-silver" , "Repairman" , "Rest-harrow" , "Rest-home" , "Retail" , "Revel-rout" , "Rheumatoid-arthritis" , "Rice-shell" , "Right-about" , "Right-angled" , "Right-handedness" ,
        "Right-of-way" , "Right-wing" , "Right-winger" , "Rights-of-way" , "Rip-off" , "Riverbank" , "Riverbanks" , "Rix-dollar" , "Road-show" , "Roadrunner" , "Robe-de-chambre" , "Rock-and-roll" , "Rocking-chair" ,
        "Rocking-horse" , "Rocking-stone" , "Roll-off" , "Roll-out" , "Rolling-pin" , "Rollout" , "Rolly-poly" , "Rolly-pooly" , "Roly-poly" , "Room" , "Root-and-branch" , "Rope-yarn" , "Rose-rial" , "Roughing-in" ,
        "Rouly-pouly" , "Ruba-dub" , "Rubberband" , "Rule-monger" , "Run-in" , "Run-through" , "Runaway" , "Runner-up" , "Runners-up" , "Runway" , "Rush-bearing" , "Ruta-baga" , "Safe-conduct" , "Safe-keeping" ,
        "Safe-pledge" , "Sagebrush" , "Sailboat" , "Saint-" , "Simonian" , "Saint-" , "Simonianism" , "Salal-berry" , "Salesclerk" , "Saltwater" , "Sance-bell" , "Sand-blasting" , "Sanders-blue" , "Sandlot" ,
        "Sandpaper" , "Sandstone" , "Sang-froid" , "Sans-culotte" , "Sans-culottism" , "Sauce-alone" , "Saucepan" , "Saunders-blue" , "Save-all" , "Saw-set" , "Saw-whet" , "Saw-wort" , "Saw-wrest" , "Sawdust" ,
        "Sax-tuba" , "Say-so" , "Scale-down" , "Scale-up" , "Scape-wheel" , "Scapegoat" , "Scarecrow" , "Scatter-brain" , "Scatterbrain" , "School-teacher" , "Schoolbook" , "Schoolboy" , "Schoolbus" , "Schoolhouse" ,
        "Schoolwork" , "Scotch-hopper" , "Scrap-heap" , "Screenplay" , "Screw-driver" , "Screw-up" , "Screwdriver" , "Sea-bar" , "Sea-blubber" , "Sea-ear" , "Sea-gait" , "Sea-gate" , "Sea-green" , "Sea-maid" ,
        "Sea-mail" , "Sea-mell" , "Sea-orb" , "Sea-pen" , "Sea-trout" , "Seacoast" , "Seafood" , "Seagull" , "Sealing-off" , "Seaman" , "Seaport" , "Seashell" , "Seashore" , "Seaside" , "Seaweed" , "Second-best" ,
        "Second-hand" , "Second-lieutenant" , "Second-sight" , "Secondhand" , "Secretaries-general" , "Secretary-general" , "Secundo-geniture" , "See-saw" , "See-sawed" , "See-sawing" , "See-saws" , "Seed-lac" ,
        "Seek-no-further" , "Seek-sorrow" , "Seesaw" , "Self-abasement" , "Self-abhorrence" , "Self-abnegation" , "Self-abuse" , "Self-action" , "Self-activity" , "Self-admiration" , "Self-affairs" ,
        "Self-aggrandizement" , "Self-annihilation" , "Self-applause" , "Self-assertion" , "Self-centration" , "Self-charity" , "Self-color" , "Self-command" , "Self-commune" , "Self-communion" , "Self-complacency" ,
        "Self-conceit" , "Self-concern" , "Self-condemnation" , "Self-confidence" , "Self-consciousness" , "Self-consistency" , "Self-contradiction" , "Self-control" , "Self-conviction" , "Self-culture" ,
        "Self-deceit" , "Self-deception" , "Self-defence" , "Self-defense" , "Self-degradation" , "Self-delation" , "Self-delusion" , "Self-denial" , "Self-destroyer" , "Self-destruction" , "Self-determination" ,
        "Self-devotement" , "Self-devotion" , "Self-discipline" , "Self-distrust" , "Self-effacing" , "Self-enjoyment" , "Self-esteem" , "Self-estimation" , "Self-evidence" , "Self-evolution" , "Self-exaltation" ,
        "Self-examinant" , "Self-examination" , "Self-existence" , "Self-exposure" , "Self-fertilization" , "Self-government" , "Self-gratulation" , "Self-heal" , "Self-help" , "Self-homicide" , "Self-ignorance" ,
        "Self-imposture" , "Self-improvement" , "Self-indignation" , "Self-interest" , "Self-involution" , "Self-justifier" , "Self-knowledge" , "Self-life" , "Self-locking" , "Self-love" , "Self-mettle" ,
        "Self-motion" , "Self-murderer" , "Self-neglecting" , "Self-opinion" , "Self-parody" , "Self-partiality" , "Self-pity" , "Self-possession" , "Self-praise" , "Self-preservation" , "Self-protection" ,
        "Self-punishment" , "Self-reliance" , "Self-renunciation" , "Self-repellency" , "Self-repetition" , "Self-reproach" , "Self-reproof" , "Self-respect" , "Self-restraint" , "Self-reverence" ,
        "Self-righteousness" , "Self-rule" , "Self-sacrifice" , "Self-sacrificing" , "Self-satisfaction" , "Self-seeker" , "Self-seeking" , "Self-slaughter" , "Self-sufficiency" , "Self-teaching" ,
        "Self-tormentor" , "Self-torture" , "Self-trust" , "Self-view" , "Self-will" , "Self-willedness" , "Self-worship" , "Self-wrong" , "Sell-off" , "Sell-offs" , "Selling-off" , "Seltzo-gene" ,
        "Semi-" , "Arian" , "Semi-" , "Arianism" , "Semi-basement" , "Semi-governmental" , "Semi-" , "Pelagian" , "Semi-" , "Pelagianism" , "Send-off" , "Send-offs" , "Send-up" , "Sergeant-major" ,
        "Series" , "Set-aside" , "Set-fair" , "Set-to" , "Setback" , "Setup" , "Seven-shooter" , "Seven-thirties" , "Seven-up" , "Seventy-four" , "Sewing-machine" , "Shad-spirit" , "Shad-waiter" ,
        "Shag-rag" , "Shake-up" , "Shakeup" , "Shame-proof" , "Sharecropper" , "Sharp-shooting" , "Sharpshooter" , "Sheep's-eye" , "Sheep's-foot" , "Sheep-dog" , "Sheep-shearer" , "Sheep-shearing" ,
        "Sheepskin" , "Shell-lac" , "Shellfish" , "Shield-bearer" , "Shilly-shally" , "Shipwreck" , "Shiver-spar" , "Shoe-in" , "Shoeing-horn" , "Shoelace" , "Shoemaker" , "Shoo-in" , "Shoot-down" ,
        "Shoplifter" , "Shortbread" , "Shorthand" , "Shortstop" , "Shot-clog" , "Shot-in-the-arm" , "Shotgun" , "Shoulder-to-shoulder" , "Show-and-tell" , "Show-off" , "Showoff" , "Showplace" , "Showroom" ,
        "Shut-off" , "Shutdown" , "Shwan-pan" , "Sickbed" , "Side order" , "Side road" , "Side street" , "Side-by-side" , "Side-step" , "Side-taking" , "Sideboard" , "Sideburns" , "Sidecar" , "Sidekick" ,
        "Sideline" , "Sideshow" , "Sidetrack" , "Sidewalk" , "Sight-hole" , "Sight-seeing" , "Sight-seer" , "Sight-shot" , "Sign-off" , "Sign-up" , "Signed-off" , "Signing-off" , "Signing-on" , "Silkworm" ,
        "Silversmith" , "Silverware" , "Sing-along" , "Sing-sing" , "Sing-song" , "Sing-songs" , "Single-foot" , "Sinkhole" , "Sister-in-law" , "Sisterhood" , "Sit-in" , "Sit-ins" , "Sit-up" , "Sit-ups" ,
        "Six-footer" , "Six-gun" , "Six-pack" , "Six-packs" , "Six-shooter" , "Six-wheeler" , "Sixfold" , "Skateboard" , "Ski-lift" , "Skintight" , "Skittle-dog" , "Skullcap" , "Skylark" , "Skylight" ,
        "Skyscraper" , "Slang-whanger" , "Slap-down" , "Slapstick" , "Slaughterhouse" , "Sled-dog" , "Sleep-at-noon" , "Sleepwalking" , "Sleight-of-hand" , "Slip-on" , "Slip-up" , "Slit-shell" , "Slowdown" ,
        "Slumlord" , "Small-arm" , "Small-caps" , "Small-holders" , "Smell-feast" , "Snaffle-bit" , "Snake's-head" , "Snake's-tongue" , "Snakeskin" , "Sneak-cup" , "Snip-snap" , "Snipper-snaper" , "Snow-broth" ,
        "Snow-melt" , "Snowball" , "Snowbank" , "Snowbird" , "Snowdrift" , "Snowfall" , "Snowflake" , "Snowman" , "Snowplow" , "Snowshoe" , "Snowstorm" , "So-and-so" , "So-far" , "Soft-drink" , "Softball" ,
        "Software" , "Sol-fa" , "Sol-faing" , "Solicitor-general" , "Some-where" , "Somebody" , "Someday" , "Somehow" , "Someone" , "Someplace" , "Something" , "Sometime" , "Sometimes" , "Somewhat" , "Somewhere" ,
        "Son-in-law" , "Son-of-a-bitch" , "Songbird" , "Sons-of-bitches" , "Sound-alike" , "Sound-board" , "Sounding-board" , "Soundproof" , "Soundtrack" , "Soupe-maigre" , "South-east" , "South-eastwards" ,
        "South-western" , "South-westward" , "South-westwards" , "Southeast" , "Southwest" , "Soybean" , "Spaceship" , "Spacewalk" , "Spatter-dock" , "Spattling-poppy" , "Spearmint" , "Speckled-belly" ,
        "Speckled-bill" , "Spillway" , "Spin-off" , "Spit-venom" , "Splanchno-skeleton" , "Split-off" , "Split-tail" , "Split-up" , "Spokesperson" , "Spoon-meat" , "Sportsman" , "Spotlight" , "Spouse-breach" ,
        "Spreadsheet" , "Springtime" , "Spur-royal" , "Spur-shell" , "Spurling-line" , "Spurn-water" , "Squab-chick" , "Square-toed" , "Square-toes" , "Squaring-off" , "Squaring-up" , "Squint-eye" , "Stack-guard" ,
        "Stag-evil" , "Stagehand" , "Stake-driver" , "Stalemate" , "Stalking-horse" , "Stall-feeding" , "Stand-by" , "Stand-down" , "Stand-in" , "Stand-off" , "Standard-wing" , "Standby" , "Stander-by" ,
        "Standoff" , "Standout" , "Standpipe" , "Standpoint" , "Star-chamber" , "Star-read" , "Starfish" , "Starlight" , "Start-up" , "Startup" , "States-general" , "Statewide" , "Steamboat" , "Steamship" ,
        "Stem-winder" , "Step-by-step" , "Stepbrother" , "Stepchild" , "Stepfather" , "Stepmother" , "Stepping-stone" , "Stepsister" , "Stepson" , "Stereo-chemistry" , "Stern-wheeler" , "Stick-lac" , "Stick-seed" ,
        "Stick-tight" , "Stiff-neckedness" , "Still-burn" , "Still-hunt" , "Stock-in-trade" , "Stockroom" , "Stone-horse" , "Stonewall" , "Stop-gap" , "Stop-off" , "Stoplight" , "Stopping-out" , "Stopwatch" ,
        "Storerooms" , "Storm-door" , "Story-teller" , "Story-telling" , "Story-writer" , "Storyteller" , "Straightforward" , "Strait-jacket" , "Strait-waistcoat" , "Strangle-hold" , "Straw-cutter" , "Strawberry" ,
        "Strip-leaf" , "Strong-points" , "Strong-water" , "Strongbox" , "Stronghold" , "Stud-horse" , "Stumbling-block" , "Stumbling-stone" , "Sub-base" , "Sub-bass" , "Sub-committee" , "Sub-contract" ,
        "Sub-director" , "Sub-function" , "Sub-licensed" , "Sub-paragraph" , "Sub-regional" , "Sub-section" , "Sub-species" , "Sub-total" , "Subject-matter" , "Subway" , "Suchlike" , "Sudden-death" , "Sugar-house" ,
        "Sugarcoat" , "Suitcase" , "Sulphur-bottom" , "Summertime" , "Sun-burner" , "Sunbaked" , "Sunbathe" , "Sunburn" , "Sunday" , "Sundial" , "Sundown" , "Sunfish" , "Sunflower" , "Sunglasses" , "Sunlight" ,
        "Sunlit" , "Sunray" , "Sunrise" , "Sunroof" , "Sunset" , "Sunshade" , "Sunshine" , "Sunspot" , "Sunstroke" , "Suntan" , "Sunup" , "Supercargo" , "Supercharge" , "Supercool" , "Superego" , "Superfine" ,
        "Supergiant" , "Superhero" , "Superhighway" , "Superhighways" , "Superhuman" , "Superimpose" , "Superman" , "Supermarket" , "Supermen" , "Supernatural" , "Superpower" , "Superscript" , "Supersensitive" ,
        "Supersonic" , "Superstar" , "Superstrong" , "Superstructure" , "Supertanker" , "Superweapon" , "Superwoman" , "Supple-jack" , "Supra-auricular" , "Supra-ilium" , "Surfeit-water" , "Surgeon-general" ,
        "Swan's-down" , "Swan-hopping" , "Swan-upping" , "Swans-down" , "Sward-cutter" , "Sway-bracing" , "Swear-word" , "Sweatshirt" , "Sweep-saw" , "Sweet-sop" , "Sweetheart" , "Sweetmeat" , "Swine-pox" ,
        "Switch-off" , "Switch-on" , "Swordfish" , "T-bill" , "T-bills" , "T-shirt" , "Table-land" , "Tablecloth" , "Tablespoon" , "Tabletop" , "Tableware" , "Tadpole" , "Tag-rag" , "Tagalong" , "Tail-bay" ,
        "Tail-in" , "Tail-water" , "Tailbone" , "Tailcoat" , "Tailgate" , "Taillight" , "Taillike" , "Tailpiece" , "Tailspin" , "Take-away" , "Take-in" , "Take-off" , "Take-over" , "Take-up" , "Takeoff" ,
        "Takeout" , "Takeover" , "Talebearer" , "Taleteller" , "Talk-show" , "Talking-to" , "Tallow-face" , "Tam-tam" , "Tap-in" , "Tapeworm" , "Taproom" , "Taproot" , "Taqua-nut" , "Target" , "Taskmaster" ,
        "Taxicab" , "Taxpayer" , "Te-hee" , "Tea-saucer" , "Teach-in" , "Teach-ins" , "Teacup" , "Team-up" , "Teammate" , "Teamwork" , "Teapot" , "Tear-thumb" , "Teardrop" , "Teaspoon" , "Teaze-hole" , "Tee-off" ,
        "Tee-shirt" , "Teenager" , "Teeny-boppers" , "Teeter-tail" , "Tell-tale" , "Tell-tales" , "Telltale" , "Ten-o'clock" , "Ten-pin" , "Ten-pounder" , "Ten-strike" , "Tenderfoot" , "Tenfold" , "Ter-tenant" ,
        "Terre-tenant" , "Terre-verte" , "Tete-a-tete" , "Tete-de-pont" , "Tetter-totter" , "Text-book" , "Text-hand" , "Textbook" , "Thanksgiving" , "Themselves" , "Therefore" , "Thick-knee" , "Think-tank" ,
        "Think-tanks" , "Third-borough" , "Third-parties" , "Third-penny" , "Thorough-brace" , "Three-decker" , "Three-masters" , "Three-pile" , "Three-wheelers" , "Thresh-fold" , "Through-put" , "Through-way" ,
        "Throw-crook" , "Throwaway" , "Throwback" , "Thumbs-down" , "Thunderbird" , "Thunderbolt" , "Thunderstorm" , "Tib-cat" , "Ticking-off" , "Tie-back" , "Tie-down" , "Tie-rod" , "Tie-up" , "Tierce-major" ,
        "Tiger's-foot" , "Tiger-eye" , "Tiger-foot" , "Tilt-mill" , "Tilt-up" , "Tilt-yard" , "Tim-whiskey" , "Time-and-a-half" , "Time-out" , "Time-sharing" , "Time-table" , "Timekeeper" , "Timepieces" , "Timesaving" ,
        "Timesheet" , "Timetable" , "Tip-off" , "Tip-toed" , "Tip-up" , "Tippling-house" , "Tiptoe" , "Tire-woman" , "Tiring-house" , "Tiring-room" , "Tit-for-tat" , "Title-holder" , "Title-page" , "Tittle-tattle" ,
        "Tittle-tattling" , "To-date" , "To-day" , "To-do" , "To-fall" , "To-name" , "Toadstool" , "Today" , "Toe-in" , "Toenail" , "Together" , "Tom-tom" , "Tongue-pad" , "Tongue-shell" , "Tongue-tie" , "Tonight" ,
        "Tool-maker" , "Tool-post" , "Tool-rest" , "Tool-stock" , "Toolbox" , "Toothbrush" , "Toothpaste" , "Toothpick" , "Top-armor" , "Top-block" , "Top-boots" , "Top-chain" , "Top-cloth" , "Top-draining" ,
        "Top-dressing" , "Top-hamper" , "Top-light" , "Top-rope" , "Top-shell" , "Top-tackle" , "Top-timbers" , "Top-tool" , "Tops-and-bottoms" , "Touch-box" , "Touch-me-not" , "Touch-needle" , "Touch-paper" ,
        "Touchdown" , "Tough-cake" , "Tough-head" , "Tough-pitch" , "Tous-les-mois" , "Tout-ensemble" , "Tow-head" , "Town-crier" , "Township" , "Track-road" , "Trade-mark" , "Trade-off" , "Trade-union" ,
        "Trade-unionist" , "Trade-up" , "Trades-unionist" , "Tradesman" , "Trading-in" , "Trading-off" , "Tragi-comedy" , "Trailblazer" , "Trans-migration" , "Trans-sexual" , "Tray-trip" , "Tread-softly" ,
        "Treasure-house" , "Treasure-trove" , "Trencher-man" , "Tres-tyne" , "Trigesimo-secundo" , "Tripe-de-roche" , "Triple-tail" , "Trou-de-loup" , "Trough-shell" , "Truck-driver" , "Truckle-bed" ,
        "True-blue" , "True-penny" , "Trugging-house" , "Trundle-bed" , "Truth-lover" , "Truth-teller" , "Try-square" , "Tryout" , "Tu-whit" , "Tu-whoo" , "Tube-shell" , "Tuck-net" , "Tue-iron" , "Tue-irons" ,
        "Tuf-taffeta" , "Tug-of-war" , "Tugboat" , "Tuko-tuko" , "Tulip-shell" , "Tum-tum" , "Tun-dish" , "Tune-in" , "Tune-up" , "Tuning-in" , "Turban-shell" , "Turban-top" , "Turn-buckle" , "Turn-out" ,
        "Turn-sick" , "Turnabout" , "Turnaround" , "Turnbuckle" , "Turncoat" , "Turndown" , "Turnip-shell" , "Turnkey" , "Turnoff" , "Turnout" , "Turnover" , "Turnpike" , "Turntable" , "Turtle-shell" ,
        "Turtleneck" , "Tusk-shell" , "Tut-nose" , "Tut-work" , "Tut-workman" , "Twelfth-cake" , "Twelfth-day" , "Twelfth-night" , "Twelfth-second" , "Twenty-fourmo" , "Twenty-two" , "Twire-pipe" ,
        "Twittle-twattle" , "Two-decker" , "Two-seater" , "Two-up" , "Ty-all" , "Typewriter" , "U-boat" , "Under-frames" , "Under-garment" , "Under-housemaids" , "Under-secretary" , "Underachieve" ,
        "Underact" , "Underage" , "Underarm" , "Underbelly" , "Underbid" , "Undercharge" , "Underclothes" , "Underclothing" , "Undercover" , "Undercurrent" , "Undercut" , "Underdevelop" , "Underdog" ,
        "Underestimate" , "Underexpose" , "Underfoot" , "Undergo" , "Underground" , "Undergrowth" , "Undermined" , "Undersigned" , "Undersized" , "Understatement" , "Undertake" , "Undertaker" ,
        "Undervalued" , "Undo" , "Ungka-puti" , "Unit-trusts" , "Up-line" , "Up-side" , "Upbeat" , "Upbringing" , "Upcoming" , "Update" , "Upend" , "Upgrade" , "Upheaval" , "Upheld" , "Uphill" ,
        "Uphold" , "Upkeep" , "Upland" , "Uplift" , "Uplink" , "Upload" , "Upmarket" , "Upon" , "Uppercase" , "Upperclassman" , "Uppercut" , "Uppermost" , "Upright" , "Uprising" , "Uproar" ,
        "Uproot" , "Upscale" , "Upset" , "Upshot" , "Upside" , "Upside-down" , "Upstage" , "Upstairs" , "Upstanding" , "Upstart" , "Upstate" , "Upstream" , "Upstroke" , "Uptake" , "Upthrust" ,
        "Uptight" , "Uptime" , "Uptown" , "Upturn" , "Upward" , "Upwardly-mobile" , "Upwind" , "Uran-ocher" , "Uran-ochre" 
    };

    static private string[] _Vowels = { "a", "e", "i", "o", "u" };

    static private string[] _HeightBallAnswers =
    {
        "Yes.",
        "No.",
        "You can count on it.",
        "Don't count on it.",
        "The stars have aligned, and all signs point to... Yes!",
        "God says no.",
        "Outlook good.",
        "Somewhere in another universe people have spent eons looking for the answer. But we have found it in a matter of seconds... Nope!",
        "For you, it's a yes.",
        "The answer is a cake, and the cake is a lie.",
        "Flip flop the answer is nope!",
        "Seems like you've stumbled in to the correct zone.",
        "Yes, but only on Wednesdays.",
        "The horse says neigh!",
        "Asked a dog, it said yap yap.",
        "Sorry folk, clearly a no there!",
        "That sweet lady at the bar confirmed this!"
    };

    static private string[] _PickAnswers =
    {
        "I pick \"<answer>\"",
        "I choose \"<answer>\"",
        "I'd pick \"<answer>\"",
        "\"<answer>\" seems like a good choice"
    };

    static public string[] Adjectives { get => _Adjectives; }
    static public string[] Nouns { get => _Nouns; }
    static public string[] Vowels { get => _Vowels; }
    static public string[] HeightBallAnswers { get => _HeightBallAnswers; }
    static public string[] PickAnswers { get => _PickAnswers; }
}